#!/usr/bin/env python3
"""Generate the two Claude-project pages from the app's own source.

    python3 build-template.py          # run from this directory

Outputs:

  TEMPLATE.html  snapshot. Claude pastes query rows into /*__ROWS__*/ and publishes.
                 Works for anyone, needs no Notion access, frozen at a moment in time.

  LIVE.html      live. Published ONCE with the `mcp` capability; the page queries
                 Notion through each viewer's own connector when they open it.
                 Nothing is regenerated per refresh, so there is no wait.

Both are DERIVED, never hand-maintained, and both embed the same tested adapter:

    ../roadmap-app/index.html   the renderer
    ../roadmap-app/notion.js    adapt() + reviewBaselines()
    ../roadmap-app/mapping.json field mapping and baseline-trust rules
    ./sql-shim.js                   SQL rows -> Notion page shapes

CLAUDE.md's rule is that the renderer must not be copied again; generating these is
how that rule is kept. Re-run after any change to the files above.
"""
import io, json, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
APP  = os.path.join(HERE, "..", "roadmap-app")
DS   = "collection://REPLACE_WITH_YOUR_NOTION_DATA_SOURCE_ID"

QUERY = " ".join("""
SELECT "Initiative Name" AS name, "Swimlane" AS lane, "Status" AS status, "RAG" AS rag,
       "date:Committed Date:start" AS baseline,
       "date:Delivery Dates:start" AS cd_start,
       "date:Delivery Dates:end" AS cd_end,
       "date:Discovery Dates:start" AS disc_start,
       "date:Discovery Dates:end" AS disc_end,
       "date:Discovery start:start" AS disc_legacy,
       "date:In Progress start:start" AS ip_start,
       "date:Done date:start" AS done_date,
       "Description" AS description, "Latest Update" AS latest_update,
       "date:Update Last Edited:start" AS update_at,
       "Parent item" AS parent, url
FROM "%s"
WHERE "Swimlane" IS NOT NULL
""".replace("%s", DS).split())

def read(p):
    with io.open(p, encoding="utf-8") as f:
        return f.read()

page    = read(os.path.join(APP, "index.html"))
adapter = read(os.path.join(APP, "notion.js"))
mapping = read(os.path.join(APP, "mapping.json"))
shim    = read(os.path.join(HERE, "sql-shim.js"))

if page.count("\nboot();") != 1:
    sys.exit("expected exactly one boot() call in index.html")
page = page.replace("\nboot();", "\n/* boot() removed: these pages supply their own data */")

adapter = adapter.replace(
    'module.exports = { fetchInitiatives, adapt, reviewBaselines, mapping: MAP };',
    'return { adapt: adapt, reviewBaselines: reviewBaselines, mapping: MAP };')
shim = "\n".join(l for l in shim.split("\n") if not l.startswith("if (typeof module"))

# Shared by both pages: the real adapter and the row shim.
CORE = """
<script>
/* Generated by roadmap-claude/build-template.py. Do not edit by hand.
   The adapter below is the same code the web and desktop apps run, so these pages
   canonicalise RAG, apply the swimlane filter and excludeStatus, link sub-items and
   judge baselines exactly as they do. */
var ADAPTER = (function(){
  var module = { exports: {} };
  var process = { env: {} };
  var MAPPING = __MAPPING__;
  function require(p){
    if (p === "./mapping.json") return MAPPING;
    throw new Error("unexpected require: " + p);
  }
  function fetch(){ throw new Error("this page never calls Notion directly"); }
__ADAPTER__
})();

__SHIM__

function applyLanes(){
  if (ADAPTER.mapping && ADAPTER.mapping.lanes && ADAPTER.mapping.lanes.length) {
    LANES = ADAPTER.mapping.lanes;
  }
}
function paint(rows, stampIso, badgeClass, badgeText, stampPrefix){
  var out = ADAPTER.adapt(sqlRowsToPages(rows));
  applyLanes();
  showWarnings(out.warnings);
  render(out.results);
  renderMeasuring(out.results);
  var b = document.getElementById("src");
  if (b) { b.className = "badge " + badgeClass; b.textContent = badgeText; }
  setStamp(stampIso, stampPrefix);
  return out;
}
function state(title, detail){
  var g = document.getElementById("grid");
  if (!g) return;
  g.innerHTML = "";
  var wrap = document.createElement("div");
  wrap.style.cssText = "padding:26px 18px;font-size:12.5px;color:#4b5563;line-height:1.6;max-width:640px";
  var h = document.createElement("div");
  h.style.cssText = "font-weight:700;color:#1f2430;margin-bottom:4px";
  h.textContent = title;
  var d = document.createElement("div");
  d.textContent = detail || "";
  wrap.appendChild(h);
  wrap.appendChild(d);
  g.appendChild(wrap);
}
</script>
"""
core = (CORE.replace("__MAPPING__", mapping.strip())
            .replace("__ADAPTER__", adapter)
            .replace("__SHIM__", shim))

SNAPSHOT_BOOT = """
<script>
/* Claude replaces the two markers below. Nothing else in this file should be edited. */
var ROWS = /*__ROWS__*/[];
var GENERATED_AT = /*__GENERATED_AT__*/null;
(function(){
  try {
    if (!ROWS.length) {
      state("This snapshot came out empty.",
            "No initiatives were returned when it was generated, so there is nothing to "
            + "show. Ask for a fresh one rather than reading this as an empty roadmap.");
      return;
    }
    paint(ROWS, GENERATED_AT, "snap", "Snapshot", "data as of");
  } catch (e) {
    state("Could not build this snapshot.", String(e && e.message ? e.message : e));
  }
})();
</script>
"""

LIVE_BOOT = """
<script>
/* Reads the roadmap database through the viewer's own Notion connector. */
var QUERY = __QUERY__;
var DS = __DS__;
var EXPLAIN = {
  server_not_connected: "Connect Notion in your Claude connector settings, then reload.",
  needs_reauth: "Your Notion connection needs re-authorising in Claude, then reload.",
  not_granted: "This page was not granted access to Notion in this view.",
  server_not_found: "No connector named Notion was found on this account.",
  blocked_by_policy: "Your organisation's policy blocked this request.",
  rate_limited: "Notion is rate limiting. Wait a moment and reload."
};

/* The connector's JSON normally arrives on result.payload; dig through content blocks
   if it does not. The envelope has not been observed from inside a published page, so
   this stays tolerant rather than assuming one shape. */
function rowsFrom(result){
  var p = result && result.payload;
  if (typeof p === "string") { try { p = JSON.parse(p); } catch (e) {} }
  if (!p && result && result.content && result.content.length) {
    for (var i = 0; i < result.content.length; i++) {
      var b = result.content[i];
      if (b && b.text) { try { p = JSON.parse(b.text); break; } catch (e) {} }
    }
  }
  if (Array.isArray(p)) return p;
  if (p && Array.isArray(p.results)) return p.results;
  return null;
}

var LAST_ROWS = null, LAST_AT = null;

(function(){
  // An exported copy carries its rows in the head and must never call Notion.
  if (window.__SNAPSHOT__) {
    paint(window.__SNAPSHOT__.rows, window.__SNAPSHOT__.at, "snap", "Snapshot", "data as of");
    return;
  }
  state("Loading the roadmap\\u2026", "Reading the roadmap database in Notion.");
  if (!window.claude || typeof window.claude.use !== "function") {
    state("This page needs to run inside Claude.",
          "It reads the roadmap live through your own Notion connector, so it cannot render "
          + "when opened as a plain file. Ask for an exported snapshot instead.");
    return;
  }
  window.claude.use("mcp").then(function(mcp){
    if (!mcp) {
      state("Notion is not available in this view.",
            "This page reads the roadmap through your own Notion connector. Check that Notion "
            + "is connected in your Claude settings, then reload.");
      return;
    }
    mcp.watchTool("Notion", "notion-query-data-sources",
      { data: { data_source_urls: [DS], query: QUERY } },
      function(ev){
        if (ev.type === "error") {
          var code = (ev.error && ev.error.code) || "unknown";
          state("Could not read the roadmap from Notion.",
                (EXPLAIN[code] || "") + " (" + code + ")");
          return;
        }
        var rows = rowsFrom(ev.result);
        if (!rows) {
          state("Notion replied in a shape this page did not expect.",
                "Nothing has been drawn, rather than showing a partial roadmap.");
          return;
        }
        // Zero rows renders a complete but empty roadmap, which reads as "there is no
        // work on the roadmap" rather than "you cannot see it". For most viewers the
        // real cause is Notion permissions, so say so instead of drawing empty lanes.
        if (!rows.length) {
          state("No initiatives came back from Notion.",
                "This usually means your Notion account cannot see the Initiatives "
                + "database. Open it in Notion to check, then reload this page. If you can "
                + "open it, then nothing is currently tagged with an Swimlane.");
          return;
        }
        var storedAt = ev.result && ev.result.cache && ev.result.cache.storedAt;
        LAST_ROWS = rows;
        LAST_AT = new Date(storedAt || Date.now()).toISOString();
        paint(rows, LAST_AT, "live", "Live from Notion", "updated");
        offerExport();
      },
      { cache: { staleTime: 60000 } });
  }).catch(function(e){
    state("Could not reach Notion.", String(e && e.message ? e.message : e));
  });
})();

/* ---- Export: hand the viewer a self-contained copy of what they are looking at ----
   The artifact sandbox blocks a page from starting its own download, so this goes
   through the downloads capability. It is only offered once we know the capability
   resolves and we actually have rows to bake. */
function buildSnapshot(){
  var clone = document.documentElement.cloneNode(true);
  var btn = clone.querySelector("#exportBtn");
  if (btn && btn.parentNode) btn.parentNode.removeChild(btn);

  // Correct the badge and stamp in the MARKUP: a frozen file must not carry a live
  // badge even for the moment before its scripts run.
  var cb = clone.querySelector("#src");
  if (cb) { cb.className = "badge snap"; cb.textContent = "Snapshot"; }
  var cs = clone.querySelector("#stamp");
  if (cs && LAST_AT) cs.textContent = "data as of " + new Date(LAST_AT).toLocaleString();

  // Baked rows go in the head so they are set before the boot block below runs.
  var head = clone.querySelector("head");
  var sc = document.createElement("script");
  sc.textContent = "window.__SNAPSHOT__=" + JSON.stringify({rows: LAST_ROWS, at: LAST_AT}) + ";";
  if (head) head.insertBefore(sc, head.firstChild);

  var close = "</bo" + "dy>";
  var doc = clone.outerHTML;
  return "<!doctype html>\\n" + doc;
}

function exportName(){
  var d = new Date(LAST_AT || Date.now());
  function p(n){ return (n < 10 ? "0" : "") + n; }
  return "Roadmap-" + d.getFullYear() + "-" + p(d.getMonth()+1) + "-" + p(d.getDate()) + ".html";
}

var DL_EXPLAIN = {
  extension_not_enabled: "HTML downloads are not enabled in this view. Ask Sam for an export from the desktop app.",
  too_large: "The file is too large to download here.",
  declined: "",
  rate_limited: "A download prompt is already open. Try again in a moment.",
  rejected_extension: "This view will not accept an .html download."
};

function offerExport(){
  if (!window.claude || typeof window.claude.use !== "function") return;
  window.claude.use("downloads").then(function(dl){
    if (!dl) return;                       // saves unusable here: leave the button hidden
    var btn = document.getElementById("exportBtn");
    if (!btn || !LAST_ROWS) return;
    btn.style.display = "inline";
    btn.addEventListener("click", function(){
      var was = btn.textContent;
      btn.textContent = "Preparing\\u2026"; btn.disabled = true;
      function reset(msg){
        btn.textContent = msg || was;
        btn.disabled = false;
        if (msg) setTimeout(function(){ btn.textContent = was; }, 3000);
      }
      dl.save({ filename: exportName(), data: buildSnapshot() })
        .then(function(){ reset("Saved"); })
        .catch(function(err){
          var code = (err && err.code) || "unavailable";
          var why = DL_EXPLAIN[code];
          if (why) state("Could not save the file.", why);
          reset(code === "declined" ? null : "Save failed");
        });
    });
  }).catch(function(){});
}
</script>
"""
live_boot = LIVE_BOOT.replace("__QUERY__", json.dumps(QUERY)).replace("__DS__", json.dumps(DS))


def slim(html):
    """Shrink what the model has to retype, conservatively.

    Only touches <script> and <style> blocks, and only in ways that cannot change
    meaning: drops whole lines that are nothing but a // comment, strips leading
    indentation, and removes blank lines. It never rewrites code within a line, so
    string literals and regexes are untouched — the naive lexing that would break
    them is exactly the mistake check-parity.py made twice.

    HTML outside those blocks is left alone: some of it is rendered with
    white-space:pre-wrap and indentation there is not always cosmetic.

    The /*__ROWS__*/ and /*__GENERATED_AT__*/ markers must survive verbatim; they are
    on their own lines and are not // comments, so they do.
    """
    import re as _re

    def shrink(m):
        body = m.group(2)
        keep = []
        for line in body.split("\n"):
            t = line.strip()
            if not t:
                continue
            if t.startswith("//"):
                continue
            keep.append(t)
        return m.group(1) + "\n".join(keep) + m.group(3)
    html = _re.sub(r'(<script>)([\s\S]*?)(</script>)', shrink, html)
    html = _re.sub(r'(<style>)([\s\S]*?)(</style>)', shrink, html)
    return html

# The Export button exists only on the live page. The snapshot has nothing to export,
# and the web app has no such button, so it is injected here rather than carried in the
# shared renderer where it would appear somewhere it does not work.
LIVE_BUTTON_CSS = (
    ".stamp { font-size:10.5px; color:#9aa1ac; }\n"
    ".link-btn { font-size:11px; color:#2563C9; background:none; border:none; "
    "cursor:pointer; padding:0; text-decoration:underline; }\n"
    ".link-btn[disabled] { color:#9aa1ac; cursor:default; text-decoration:none; }"
)
LIVE_BUTTON_HTML = (
    '      <span class="build" id="build"></span>\n'
    '      <button class="link-btn" id="exportBtn" style="display:none">Export</button>'
)

def with_button(html):
    if html.count(".stamp { font-size:10.5px; color:#9aa1ac; }") != 1:
        sys.exit("live build: stamp style anchor not found")
    html = html.replace(".stamp { font-size:10.5px; color:#9aa1ac; }", LIVE_BUTTON_CSS, 1)
    if html.count('      <span class="build" id="build"></span>') != 1:
        sys.exit("live build: build-span anchor not found")
    return html.replace('      <span class="build" id="build"></span>', LIVE_BUTTON_HTML, 1)

at = page.rindex("</body>")
for name, boot in (("TEMPLATE.html", SNAPSHOT_BOOT), ("LIVE.html", live_boot)):
    body = page[:at] + core + boot + page[at:]
    if name == "LIVE.html":
        body = with_button(body)
    out = slim(body)
    io.open(os.path.join(HERE, name), "w", encoding="utf-8").write(out)
    print("%-14s %d bytes" % (name, len(out)))
